version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    build: .
    user: root
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - docker_jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock